language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.3
  - nightly

script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --inline=no --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
